# Generated by Django 3.2.18 on 2023-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_column='Item_Name', max_length=200)),
                ('item_desc', models.CharField(db_column='Item_Desc', max_length=200)),
                ('item_price', models.IntegerField(db_column='Item_Price')),
            ],
            options={
                'db_table': 'tblItems',
                'managed': True,
            },
        ),
    ]
