# Generated by Django 3.2.12 on 2023-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(db_column='item_image', default='https://www.shutterstock.com/image-photo/phone-placeholder-that-can-be-both-1604743003', max_length=5000),
        ),
    ]
